# -*- coding: utf-8 -*-
"""Spliting70/30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1amtFF3sRLLQUZQiSJ5f4uYsMFFyWjjBN
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

import torch
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import GCNConv


def detect_dataset_type(df):
    cols = set(df.columns.str.lower())
    if 'class' in cols or 'v1' in cols:
        return 'creditcard'
    if {'nameorig', 'namedest'}.issubset(cols) or {'origin', 'dest'}.issubset(cols) or 'step' in cols:
        return 'transaction_log'
    return 'unknown'


#  Graph constructors

def build_graph_from_creditcard(df, k=8, pca_n=10):

    print('Building graph from creditcard-style tabular dataset...')

    label_col = None
    for c in df.columns:
        if c.lower() == 'class':
            label_col = c
            break
    if label_col is None:
        raise ValueError('creditcard dataset must contain "Class" column (0/1)')


    num = df.select_dtypes(include=[np.number]).copy()

    if 'Time' in num.columns:
        num = num.drop(columns=['Time'])

    if label_col in num.columns:
        num = num.drop(columns=[label_col])


    num = num.fillna(0)
    scaler = StandardScaler()
    Xs = scaler.fit_transform(num)


    pca = PCA(n_components=min(pca_n, Xs.shape[1]))
    Xp = pca.fit_transform(Xs)


    neigh = NearestNeighbors(n_neighbors=min(k + 1, len(Xp)), algorithm='auto')
    neigh.fit(Xp)
    distances, indices = neigh.kneighbors(Xp)


    edge_index = []
    for i, inds in enumerate(indices):
        for j in inds:
            if i == j:
                continue
            edge_index.append([i, j])

    edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous()

    x = torch.tensor(Xs, dtype=torch.float)
    y = torch.tensor(df[label_col].values.astype(int), dtype=torch.long)

    data = Data(x=x, edge_index=edge_index, y=y)
    print(f'Graph nodes: {data.num_nodes}, edges: {data.num_edges}')
    return data


def build_graph_from_transaction_log(df):

    print('Building graph from transaction-log dataset...')

    orig_col = None
    dest_col = None
    label_col = None
    for c in df.columns:
        cl = c.lower()
        if cl in ['nameorig', 'origin', 'sender', 'from'] and orig_col is None:
            orig_col = c
        if cl in ['namedest', 'dest', 'receiver', 'to'] and dest_col is None:
            dest_col = c
        if cl in ['isfraud', 'fraud', 'is_fraud'] and label_col is None:
            label_col = c
    if orig_col is None or dest_col is None or label_col is None:
        raise ValueError('transaction log must have origin/dest columns and isFraud label')


    accounts = pd.Index(pd.concat([df[orig_col], df[dest_col]]).unique())
    node2idx = {n: i for i, n in enumerate(accounts)}


    n_nodes = len(accounts)
    total_sent = np.zeros(n_nodes, dtype=float)
    total_recv = np.zeros(n_nodes, dtype=float)
    cnt_sent = np.zeros(n_nodes, dtype=float)
    cnt_recv = np.zeros(n_nodes, dtype=float)


    amount_col = None
    for c in df.columns:
        if c.lower() == 'amount':
            amount_col = c
            break


    edge_list = []
    for _, row in df.iterrows():
        u = row[orig_col]
        v = row[dest_col]
        if pd.isna(u) or pd.isna(v):
            continue
        ui = node2idx[u]
        vi = node2idx[v]
        edge_list.append([ui, vi])
        amt = float(row[amount_col]) if amount_col and pd.notna(row[amount_col]) else 0.0
        total_sent[ui] += amt
        cnt_sent[ui] += 1
        total_recv[vi] += amt
        cnt_recv[vi] += 1


    mean_sent = np.divide(total_sent, np.where(cnt_sent == 0, 1, cnt_sent)).astype(float)
    mean_recv = np.divide(total_recv, np.where(cnt_recv == 0, 1, cnt_recv)).astype(float)


    X = np.vstack([total_sent, total_recv, cnt_sent, cnt_recv, mean_sent, mean_recv]).T
    scaler = StandardScaler()
    Xs = scaler.fit_transform(X)


    node_label = np.zeros(n_nodes, dtype=int)
    for _, row in df.iterrows():
        if int(row[label_col]) == 1:
            u = row[orig_col]
            v = row[dest_col]

            if u in node2idx:
                node_label[node2idx[u]] = 1
            if v in node2idx:
                node_label[node2idx[v]] = 1


    if len(edge_list) == 0:
        raise ValueError('No edges created from transaction log')
    edge_index = torch.tensor(edge_list, dtype=torch.long).t().contiguous()
    x = torch.tensor(Xs, dtype=torch.float)
    y = torch.tensor(node_label, dtype=torch.long)

    data = Data(x=x, edge_index=edge_index, y=y)
    print(f'Graph nodes: {data.num_nodes}, edges: {data.num_edges}')
    return data


# GNN model

class GNN(torch.nn.Module):

    def __init__(self, in_channels, hidden_channels=64, out_channels=2, dropout=0.5):

        super(GNN, self).__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, hidden_channels)
        self.lin = torch.nn.Linear(hidden_channels, out_channels)
        self.dropout = dropout

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, p=self.dropout, training=self.training)
        x = self.conv2(x, edge_index)
        x = F.relu(x)
        x = self.lin(x)
        return x

def train_and_test_split(data, epochs=50, lr=0.01, weight_decay=5e-4, test_size=0.30):
    device = 'cuda' if torch.cuda.is_available() else 'cpu'

    labels = data.y.cpu().numpy()
    indices = np.arange(data.num_nodes)


    train_idx, test_idx = train_test_split(
        indices,
        test_size=test_size,
        random_state=42,
        stratify=labels
    )


    train_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    test_mask = torch.zeros(data.num_nodes, dtype=torch.bool)
    train_mask[train_idx] = True
    test_mask[test_idx] = True


    model = GNN(
        in_channels=data.num_node_features,
        hidden_channels=64,
        out_channels=2
    ).to(device)

    data_gpu = data.to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay)
    loss_fn = torch.nn.CrossEntropyLoss()


    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()
        out = model(data_gpu.x, data_gpu.edge_index)
        loss = loss_fn(out[train_mask], data_gpu.y[train_mask])
        loss.backward()
        optimizer.step()

        if (epoch + 1) % 10 == 0:
            print(f"Epoch {epoch + 1} - Loss: {loss.item():.4f}")


    model.eval()
    with torch.no_grad():
        logits = model(data_gpu.x, data_gpu.edge_index)

        logits_cpu = logits.cpu()
        probs = F.softmax(logits_cpu, dim=1)[:, 1].numpy()
        preds = logits_cpu.argmax(dim=1).numpy()
        y_true = labels


    print("\nClassification Report (70/30 Split):")
    print(classification_report(y_true[test_idx], preds[test_idx], digits=4))

    try:
        print("ROC-AUC:", roc_auc_score(y_true[test_idx], probs[test_idx]))
    except:
        print("ROC-AUC failed")



    return model


def main(path, epochs=50, lr=0.01, k=8, pca_n=10):

    if str(path).endswith('.zip'):
        df = pd.read_csv(path, compression='zip')
        print(f"Reading compressed file: {path}")
    else:
        path = Path(path)
        if not path.exists():
            print('Path not found:', path)
            print('Please ensure your CSV file is uploaded to the Colab environment and the path is correct.')
            return
        df = pd.read_csv(path)

    ds_type = detect_dataset_type(df)
    print('Detected dataset type:', ds_type)

    if ds_type == 'creditcard':
        data = build_graph_from_creditcard(df, k=k, pca_n=pca_n)
    elif ds_type == 'transaction_log':
        data = build_graph_from_transaction_log(df)
    else:
        raise ValueError('Unknown dataset type. Provide creditcard.csv style or transaction log with nameOrig/nameDest/isFraud')

    train_and_test_split(data, epochs=epochs, lr=lr, test_size = 0.30)
    print('Done.')


if __name__ == "__main__":

    DATA_PATH = "/content/creditcard.csv.zip"
    EPOCHS = 50
    LR = 0.01
    K_NN = 8
    PCA_N = 10

    print(f"Starting GNN fraud detection on: {DATA_PATH}")

    main(
        path=DATA_PATH,
        epochs=EPOCHS,
        lr=LR,
        k=K_NN,
        pca_n=PCA_N
        )